name: Build and Push Docker Image to ACR and Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v2
      with:
        login-server: azurecrd4h36xqh4cp46.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t azurecrd4h36xqh4cp46.azurecr.io/weatherapp:latest
        docker push azurecrd4h36xqh4cp46.azurecr.io/weatherapp:latest

    - name: Login to Docker Hub
      run: |
        docker login -u jjones380 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Tag Docker Image for Docker Hub
      run: |
        docker tag azurecrd4h36xqh4cp46.io/weatherapp:latest jjones380/weatherprojectimages:latest
    - name: Push Docker Image to Docker Hub
      run: |
        docker push jjones380/weatherprojectimages:latest
        


