name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to ACR
    - uses: azure/docker-login@v2
      with:
        login-server: azurecrd4h36xqh4cp46.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t azurecrd4h36xqh4cp46.azurecr.io/weatherapp:latest
        docker push azurecrd4h36xqh4cp46.azurecr.io/weatherapp:latest
        


