name: Push Docker Image to ACR

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v2
      with:
        login-server: azurecrd4h36xqh4cp46.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t azurecrd4h36xqh4cp46.azurecr.io/weatherapp:latest
        docker push azurecrd4h36xqh4cp46.azurecr.io/weatherapp:latest
