name: Build and Push Docker Image to Docker Hub

on:
  workflow_run:
    workflows: ["Run Python Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          docker login -u jjones380 -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag Docker Image for Docker Hub
        run: |
          docker build --no-cache -f ./command_line_tool/Dockerfile -t jjones380/weatherprojectimages:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push jjones380/weatherprojectimages:latest
